export const UserRol = {
  mod_users: {
    access_module: false,
    roles: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    users: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    groups: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
  },
  tasks: {
    tasks: {
      create: false,
      read: false,
      delete: false,
      update: false,
    },
    projects: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    access_module: false,
  },
  design: {
    sections: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    templates: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    navigation: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    access_module: false,
  },
  content: {
    contents: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    entities: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    categories: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    access_module: false,
  },
  tickets: {
    events: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    tickets: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    access_module: false,
  },
  bookings: {
    bookings: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    access_module: false,
    installations: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    installation_items: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    installation_state: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
  },
  payments: {
    coupons: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    mandates: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    payments: {
      create: false,
      read: false,
      delete: false,
      update: false,
    },
    access_module: false,
    method_payments: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    payments_accounts: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
  },
  organization: {
    read: false,
    update: false,
    access_module: false,
  },
  competitions: {
    competitions: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    access_module: false,
  },
  inscriptions: {
    records: {
      create: false,
      read: false,
      delete: false,
      update: false,
    },
    inscriptions: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    access_module: false,
  },
  communication: {
    push: {
      create: false,
      update: false,
      read: false,
      delete: false,
    },
    emails: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    warnings: {
      read: false,
      create: false,
      delete: false,
      update: false,
    },
    access_module: false,
  },
  access_control: {
    devices: {
      create: false,
      read_all: false,
      read_own: false,
      delete_all: false,
      delete_own: false,
      read_group: false,
      update_all: false,
      update_own: false,
      delete_group: false,
      update_group: false,
    },
    access_module: false,
  },
};
